import { StateTableData } from "./interface";

const stateData: Array<StateTableData> = [
  {
    id: "01",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "02",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "03",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "04",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "05",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "05",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "06",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "07",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "08",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "09",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },

  {
    id: "10",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "11",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "12",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "13",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "14",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "15",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "16",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "17",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "18",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "19",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "20",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "21",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "22",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "23",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "24",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "25",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "26",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "27",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "28",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "29",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "30",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "31",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "32",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "33",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "34",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "35",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "36",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "37",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "38",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "39",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "40",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "41",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "42",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "43",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "44",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "45",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "46",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "47",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "48",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "49",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "50",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "51",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "52",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "53",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "54",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
];

export { stateData };
