import { StateTableData } from "./interface";

const stateData: Array<StateTableData> = [
  {
    id: "01",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "01",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "01",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "01",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "01",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "01",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "01",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "01",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
  {
    id: "01",
    pic: "adfasdfa/asdfasdfasfdsa",
    name: "腾达 Powar Mate 6",
    brandName: "腾达",
    price: "4888",
    proNO: "12aa55ss99",
    publishState: 1,
    newProState: 1,
    recommandState: 1,
    sort: "0",
    sales: "300",
    reviewState: "已审核",
  },
];

export { stateData };
